source 'https://rubygems.org'

gem 'sinatra', '~> 2.0'
gem 'sinatra-contrib'
gem 'dry-validation'
gem 'dry-transaction'
gem 'shotgun'
gem 'thin'
gem 'pg'
gem 'pry'
gem 'rake'
gem 'activerecord'
gem 'sinatra-activerecord'
